"""add_document_metadata

Revision ID: e3873a40d7c3
Revises: b4a986725006
Create Date: 2026-10-09 00:30:03.833556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3873a40d7c3'
down_revision: Union[str, Sequence[str], None] = 'b4a986725006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('file_hash', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('extracted_text_status', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('classification_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_column('documents', 'classification_status')
    op.drop_column('documents', 'extracted_text_status')
    op.drop_column('documents', 'file_hash')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
