import { RJSCServiceRule, EntityType } from './types';

export const services: RJSCServiceRule[] = [
  {
    id: 'name-clearance',
    serviceName: 'Name Clearance',
    entityTypes: [EntityType.PRIVATE_COMPANY, EntityType.PUBLIC_COMPANY, EntityType.SOCIETY, EntityType.TRADE_ORGANIZATION],
    category: 'Registration',
    description: 'Name clearance for new entities.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_NAME_CLEARANCE_COMPANY', // Handled dynamically in getFeeRule
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_CITIZEN_CHARTER_2025'],
    sourceStatus: 'VERIFIED'
  },
  {
    id: 'name-clearance-review',
    serviceName: 'Name Clearance Review',
    entityTypes: [EntityType.PRIVATE_COMPANY, EntityType.PUBLIC_COMPANY, EntityType.SOCIETY, EntityType.TRADE_ORGANIZATION],
    category: 'Registration',
    description: 'Review of rejected or expired name clearance.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_NAME_CLEARANCE_REVIEW',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_CITIZEN_CHARTER_2025'],
    sourceStatus: 'VERIFIED'
  },
  {
    id: 'private-company-registration',
    serviceName: 'Private Company Registration',
    entityTypes: [EntityType.PRIVATE_COMPANY],
    category: 'Registration',
    description: 'Registration of a new private company.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_PVT_REGISTRATION',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_REG_FEE_SCHEDULE'],
    sourceStatus: 'NEEDS_SOURCE_REVIEW' // Documents not fully structured yet
  },
  {
    id: 'public-company-registration',
    serviceName: 'Public Company Registration',
    entityTypes: [EntityType.PUBLIC_COMPANY],
    category: 'Registration',
    description: 'Registration of a new public company.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_PUB_REGISTRATION',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_REG_FEE_SCHEDULE'],
    sourceStatus: 'VERIFIED'
  },
  {
    id: 'annual-return',
    serviceName: 'Annual Return / Returns Filing',
    entityTypes: [EntityType.PRIVATE_COMPANY, EntityType.PUBLIC_COMPANY, EntityType.FOREIGN_COMPANY, EntityType.TRADE_ORGANIZATION],
    category: 'Returns',
    description: 'Filing of annual returns.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_COMP_RETURN',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_RETURN_FEE_SCHEDULE'],
    sourceStatus: 'NEEDS_SOURCE_REVIEW'
  },
  {
    id: 'change-return-form-xii',
    serviceName: 'Change Return / Form XII',
    entityTypes: [EntityType.PRIVATE_COMPANY, EntityType.PUBLIC_COMPANY],
    category: 'Returns',
    description: 'Filing of Form XII for changes.',
    requiredDocuments: ['DOC_FORM_XII', 'DOC_FORM_IX', 'DOC_E_TIN', 'DOC_DIR_MEETING_MINUTES', 'DOC_DIR_NID'],
    checklist: [],
    feeRuleId: 'FEE_FORM_XII',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_CITIZEN_CHARTER_2025', 'RJSC_RETURN_FEE_SCHEDULE'],
    sourceStatus: 'VERIFIED'
  },
  {
    id: 'registered-office-change-form-vi',
    serviceName: 'Registered Office Change / Form VI',
    entityTypes: [EntityType.PRIVATE_COMPANY, EntityType.PUBLIC_COMPANY],
    category: 'Returns',
    description: 'Change of registered office.',
    requiredDocuments: ['DOC_FORM_VI', 'DOC_DIR_MEETING_MINUTES_VI'],
    checklist: [],
    feeRuleId: 'FEE_FORM_VI',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_CITIZEN_CHARTER_2025', 'RJSC_RETURN_FEE_SCHEDULE'],
    sourceStatus: 'VERIFIED'
  },
  {
    id: 'certified-copy',
    serviceName: 'Certified Copy',
    entityTypes: [EntityType.PRIVATE_COMPANY, EntityType.PUBLIC_COMPANY, EntityType.FOREIGN_COMPANY, EntityType.SOCIETY, EntityType.PARTNERSHIP, EntityType.TRADE_ORGANIZATION],
    category: 'Certified Copies',
    description: 'Request for certified copies.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_CERTIFIED_COPY',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_CERT_COPY_FEE_SCHEDULE'],
    sourceStatus: 'NEEDS_SOURCE_REVIEW'
  },
  {
    id: 'inspection-of-records',
    serviceName: 'Inspection of Records',
    entityTypes: [EntityType.PRIVATE_COMPANY, EntityType.PUBLIC_COMPANY, EntityType.FOREIGN_COMPANY, EntityType.SOCIETY, EntityType.PARTNERSHIP, EntityType.TRADE_ORGANIZATION],
    category: 'Certified Copies',
    description: 'Inspection of records.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_CERTIFIED_COPY',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_CERT_COPY_FEE_SCHEDULE'],
    sourceStatus: 'NEEDS_SOURCE_REVIEW'
  },
  {
    id: 'mortgage-charge-registration',
    serviceName: 'Mortgage / Charge Registration',
    entityTypes: [EntityType.PRIVATE_COMPANY, EntityType.PUBLIC_COMPANY, EntityType.FOREIGN_COMPANY, EntityType.TRADE_ORGANIZATION],
    category: 'Mortgage',
    description: 'Registration of mortgage or charge.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_MORTGAGE_COMPANY',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_FEE_GAZETTE_2023'],
    sourceStatus: 'VERIFIED'
  },
  {
    id: 'receiver-appointment',
    serviceName: 'Receiver Appointment',
    entityTypes: [EntityType.PRIVATE_COMPANY, EntityType.PUBLIC_COMPANY, EntityType.FOREIGN_COMPANY, EntityType.TRADE_ORGANIZATION],
    category: 'Mortgage',
    description: 'Appointment of receiver.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_RECEIVER',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_FEE_GAZETTE_2023'],
    sourceStatus: 'VERIFIED'
  },
  {
    id: 'society-registration',
    serviceName: 'Society Registration',
    entityTypes: [EntityType.SOCIETY],
    category: 'Registration',
    description: 'Registration of a new society.',
    requiredDocuments: ['DOC_SOC_REG_MOA', 'DOC_SOC_REG_NAME', 'DOC_SOC_REG_OBJECTS', 'DOC_SOC_REG_GOV_BODY', 'DOC_SOC_REG_RULES', 'DOC_SOC_REG_RULES_CERT'],
    checklist: [],
    feeRuleId: 'FEE_SOC_REGISTRATION',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['SRA_1860_SEC_2', 'RJSC_REG_FEE_SCHEDULE'],
    sourceStatus: 'VERIFIED'
  },
  {
    id: 'society-return-filing',
    serviceName: 'Society Return Filing',
    entityTypes: [EntityType.SOCIETY],
    category: 'Returns',
    description: 'Filing of society returns.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_SOC_RETURN',
    deadlineRuleId: 'DEADLINE_SOC_ANNUAL_LIST',
    nextAction: null,
    legalReferences: ['SRA_1860_SEC_4', 'RJSC_RETURN_FEE_SCHEDULE'],
    sourceStatus: 'VERIFIED'
  },
  {
    id: 'partnership-forms',
    serviceName: 'Partnership Form II / V / VI',
    entityTypes: [EntityType.PARTNERSHIP],
    category: 'Returns',
    description: 'Filing of Partnership forms.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_PARTNERSHIP_FORM',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_RETURN_FEE_SCHEDULE'],
    sourceStatus: 'NEEDS_SOURCE_REVIEW'
  },
  {
    id: 'winding-up',
    serviceName: 'Winding Up',
    entityTypes: [EntityType.PRIVATE_COMPANY, EntityType.PUBLIC_COMPANY],
    category: 'Winding Up',
    description: 'Winding up of a company.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_WINDING_UP',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_WINDING_UP_FEE_SCHEDULE'],
    sourceStatus: 'NEEDS_SOURCE_REVIEW'
  },
  {
    id: 'other-document-filing',
    serviceName: 'Generic Other Document Filing',
    entityTypes: [EntityType.TRADE_ORGANIZATION], // Or ANY non-share capital entity as supported later
    category: 'Returns',
    description: 'Generic other document filing.',
    requiredDocuments: [],
    checklist: [],
    feeRuleId: 'FEE_OTHER_DOCUMENT_NON_SHARE_CAPITAL',
    deadlineRuleId: null,
    nextAction: null,
    legalReferences: ['RJSC_FEE_GAZETTE_2023'],
    sourceStatus: 'VERIFIED'
  }
];

export const getServiceRuleById = (serviceId: string, entityType: EntityType): RJSCServiceRule | undefined => {
  return services.find(s => s.id === serviceId && s.entityTypes.includes(entityType));
};
